INSERT INTO genre (name)
VALUES ('Rock'),
       ('Pop'),
       ('Jazz'),
       ('Classical'),
       ('Hip Hop'),
       ('Electronic'),
       ('Reggae'),
       ('Blues'),
       ('Country'),
       ('Metal'),
       ('Folk'),
       ('Soul'),
       ('Punk'),
       ('Disco'),
       ('Funk'),
       ('R&B'),
       ('Gospel'),
       ('Latin'),
       ('Opera'),
       ('Techno');